# -*- coding: utf-8 -*-
"""Email Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCJxNzru9xGkhSwR9UQY8Xv9jPLif0Re

Level-1 Task-3 Email Validator

Develop a Python function that validates whether a given string is a valid email address.
"""

import re

def is_valid_email(email):
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

    if re.match(pattern, email):
        return True
    else:
        return False

email1 = "khushi.soni.5339@gmail.com"
email2 = "khushi.soni_email.com"

print(is_valid_email(email1))
print(is_valid_email(email2))